instrumentation:
  root: src
  include-all-sources: true
  verbose: true
  excludes: ['**/view/**', '**/botPage/utils/**', '**/translations/**', '**/indexPage/**', 'botPage/index.js', 'common/calls.js', 'botPage/bot/index.js']
reporting:
  dir: "coverage"
