// watchers
export const UPDATE_WAITING_FOR_PURCHASE = 'UPDATE_WAITING_FOR_PURCHASE';
// proposals
export const REQUESTED_PROPOSAL = 'REQUESTED_PROPOSAL';
export const RECEIVED_PROPOSAL = 'RECEIVED_PROPOSAL';
export const FORGOTTEN_PROPOSAL = 'FORGOTTEN_PROPOSAL';
export const RECEIVE_ALL_PROPOSALS = 'RECEIVE_ALL_PROPOSALS';
export const CLEAR_ALL_PROPOSALS = 'CLEAR_ALL_PROPOSALS';
export const UPDATE_PROPOSAL = 'UPDATE_PROPOSAL';
export const PROPOSALS_NOT_READY = 'PROPOSALS_NOT_READY';
export const ADD_FORGOTTEN_PROPOSAL_ID = 'ADD_FORGOTTEN_PROPOSAL_ID';
export const REMOVE_FORGOTTEN_PROPOSAL_ID = 'REMOVE_FORGOTTEN_PROPOSAL_ID';
export const RENEW_PROPOSALS = 'RENEW_PROPOSALS';

export const STOP_BECAUSE_OF_ERROR = 'STOP_BECAUSE_OF_ERROR';
export const INVALID = 'INVALID';
export const START = 'START';
export const PURCHASE_UNSUCCESSFULLY = 'PURCHASE_UNSUCCESSFULLY';
export const PURCHASE_SUCCESSFULLY = 'PURCHASE_SUCCESSFULLY';
export const RECEIVE_OPEN_CONTRACT = 'RECEIVE_OPEN_CONTRACT';
export const SELL_FAILED = 'SELL_FAILED';
export const SELL_SUCCESSFULLY = 'SELL_SUCCESSFULLY';
export const TICKS_RECEIVED = 'TICKS_RECEIVED';
export const UPDATE_RECEIVED_BALANCE = 'UPDATE_RECEIVED_BALANCE';
export const ADD_TRADE_OPTION = 'ADD_TRADE_OPTION';
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const NEW_TICK = 'NEW_TICK';
export const INITIALIZE = 'INITIALIZE';
export const REQUEST_PURCHASE = 'REQUEST_PURCHASE';
export const EXIT_SCOPE = 'EXIT_SCOPE';
export const CONTINUE_SCOPE = 'CONTINUE_SCOPE';
// SAGA actions
export const INIT_SAGA = 'INIT_SAGA';
export const START_SAGA = 'START_SAGA';
export const WATCH_SAGA = 'WATCH_SAGA';
export const PURCHASE_SAGA = 'PURCHASE_SAGA';
