// proposals
export const REQUESTED_PROPOSAL = 'REQUESTED_PROPOSAL';
export const RECEIVED_PROPOSAL = 'RECEIVED_PROPOSAL';
export const FORGOTTEN_PROPOSAL = 'FORGOTTEN_PROPOSAL';
// watchers
export const WAITING_FOR_PURCHASE = 'WAITING_FOR_PURCHASE';
